---
- hosts: Master
  become: true
  become_method: sudo
  vars_files:
   - secret.yml
   
  tasks:    
    - name: Create Voulme for Containers
      docker_volume:
        name: Volume1

    - name: Create Custom Docker Network
      docker_network:
       name: AppNet
       driver: overlay

    - name: Create Database container
      docker_swarm_service:
        name:  Database
        image: postgres   
        state: present
        replicas: 3
        env: 
           POSTGRES_USER: "{{mysql_user}}"
           POSTGRES_PASSWORD: "{{mysql_password}}"
        mounts :
          - source: Volume1
            target: /var/lib/postgresql/data
            type: volume  
        publish :
          - mode: ingress
            published_port: 5432   
            target_port: 5432
        networks:
          - AppNet
        healthcheck: 
          test: ["CMD", "pg_isready"]
          interval: 1m
          timeout: 10s
          retries: 3
          start_period: 30s 
        restart_config:
           condition: on-failure
           delay: 5s
           max_attempts: 3
           window: 120s

    
    - name: Create Wildfly container    
      docker_swarm_service:
        name: "Wildfly-{{item.name}}"
        image: kmmitul/wildfly_custom
        state: present   
        replicas: 3
        networks:
            - AppNet   
        publish :
          - mode: ingress
            published_port: "{{item.console_port}}"   
            target_port: 9990
     
          - mode: ingress
            published_port: "{{item.http_port}}"
            target_port: 8080

        env: 
          POSTGRES_CONNECTION: jdbc:postgresql://Database/postgres
          POSTGRES_USER: "{{mysql_user}}"
          POSTGRES_PASSWORD: "{{mysql_password}}"


        healthcheck: 
          test: ["CMD", "curl", "--fail", "http://localhost:9990"]
          interval: 1m
          timeout: 10s
          retries: 3
          start_period: 30s 

        restart_config:
           condition: on-failure
           delay: 5s
           max_attempts: 3
           window: 120s     
            
      loop:
         - {http_port: 8000, console_port: 9000,  name: admin}
         - {http_port: 8001, console_port: 9001,  name: line}
         - {http_port: 8002, console_port: 9002,  name: analyze}    
      
   
        
