---
- hosts: Master
  become: true
  become_method: sudo
  vars_files:
   - secret.yml
   
  tasks:    

    - name: Log into DockerHub
      docker_login:
        username: "{{docker_user}}"
        password: "{{docker_pass}}"   
    
    - name: Create Wildfly container    
      docker_swarm_service:
        name: Wildfly
        image: kmmitul/gnet
        state: present   
        replicas: 2
        publish :
          - mode: ingress
            published_port: 9000   
            target_port: 9990     
          - mode: ingress
            published_port: 8000
            target_port: 8080
        env: 
          POSTGRES_CONNECTION: jdbc:postgresql://10.250.25.201/mydb
          POSTGRES_USER: "{{mysql_user}}"
          POSTGRES_PASSWORD: "{{mysql_password}}"
        healthcheck: 
          test: ["CMD", "curl", "--fail", "http://localhost:9990"]
          interval: 1m
          timeout: 10s
          retries: 3
          start_period: 30s 
        restart_config:
           condition: on-failure
           delay: 5s
           max_attempts: 3
           window: 120s     
         
